=begin
#Payments-VPN

#Esta API fornece os serviços de pagamento do Banco do Brasil.

OpenAPI spec version: 3.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BancoBrasilPayments::RootTypeForBatchTransferGETResponseObject
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RootTypeForBatchTransferGETResponseObject' do
  before do
    # run before each test
    @instance = BancoBrasilPayments::RootTypeForBatchTransferGETResponseObject.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RootTypeForBatchTransferGETResponseObject' do
    it 'should create an instance of RootTypeForBatchTransferGETResponseObject' do
      expect(@instance).to be_instance_of(BancoBrasilPayments::RootTypeForBatchTransferGETResponseObject)
    end
  end
  describe 'test attribute "index"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "payments_quantity"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "payments_list"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
